name: Create Pull Request from Staging to Master

on:
  workflow_dispatch: # Triggered by the first workflow

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure Git (Set identity for the runner)
      - name: Configure Git
        run: |
          git config --global user.email "abusiraj84@gmail.com"
          git config --global user.name "abusiraj84"

      # Step 3: Check if the master branch exists, and create it if it doesn't
      - name: Ensure master branch exists without pushing changes
        run: |
          if ! git ls-remote --exit-code --heads origin master; then
            # Create an orphan branch for master with no changes from staging
            git checkout --orphan master
            git rm -rf .
            echo "# Master branch" > README.md
            git add README.md
            git commit -m "Initial commit for master branch"
            git push origin master
          else
            echo "Master branch already exists"
          fi

      # Step 4: Create a pull request from staging to master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master # Target branch (master)
          branch: staging # Source branch (staging)
          title: "Pull request from staging to master"
          body: "This is an automated pull request created after syncing main to staging."
