name: Build, Deploy, and Create PR

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.17.0"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the build script
      - name: Run build
        run: npm run build

      # Step 5: Remove unnecessary files
      - name: Remove unnecessary files
        shell: bash
        run: |
          shopt -s extglob
          rm -rf !(dist|classes|plugin.php)

      # Step 5.1: Remove the .github folder and .gitignore
      - name: Remove .github folder and .gitignore
        run: |
          rm -rf .github
          rm -rf .gitignore

      # Step 6: Configure Git
      - name: Configure Git
        run: |
          git config --global user.email "abusiraj84@gmail.com"
          git config --global user.name "abusiraj84"

      # Step 7: Commit and push the changes to staging
      - name: Commit and push changes to staging
        run: |
          git add -A  # Stage all changes, including file deletions
          git commit -m "Deploy plugin with only dist, classes, and plugin.php" || echo "No changes to commit"
          git push origin HEAD:staging --force

      # Step 8: Check if master exists, create if it doesn't (without any changes from staging)
      - name: Ensure master branch exists
        run: |
          if ! git ls-remote --exit-code --heads origin master; then
            git checkout -b master main
            git push origin master
          else
            echo "Master branch already exists"
          fi

      # Step 9: Create a pull request from staging to master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master # Target branch (master)
          branch: staging # Source branch (staging)
          title: "Pull request from staging to master"
          body: "This is an automated pull request created after a successful build and deployment to staging."
