name: Sync main to staging

on:
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure Git (Set identity for the runner)
      - name: Configure Git
        run: |
          git config --global user.email "abusiraj84@gmail.com"
          git config --global user.name "abusiraj84"

      # Step 3: Push main to staging
      - name: Push main to staging
        run: |
          git fetch origin
          git checkout main
          git pull origin main
          git push origin main:staging --force

      # Step 4: Trigger second workflow
      - name: Trigger pull request workflow
        uses: actions/github-script@v4
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'create-pull-request.yml', # The filename of the second workflow
              ref: 'main'  # Trigger the second workflow on the main branch
            })
