name: Build and Deploy

on:
  push:
    branches:
      - main # Or whichever branch you want to trigger on

jobs:
  # Job 1: Checkout Code
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensure all branches are available

  # Job 2: Build Project
  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.12.0"

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

  # Job 3: Clean up Unnecessary Files
  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Remove unnecessary files
        shell: bash
        run: |
          shopt -s extglob
          rm -rf !(dist|classes|plugin.php)

      - name: Remove .github folder
        run: rm -rf .github

  # Job 4: Commit and Push to Staging
  push-to-staging:
    runs-on: ubuntu-latest
    needs: cleanup
    steps:
      - name: Configure Git
        run: |
          git config --global user.email "abusiraj84@gmail.com"
          git config --global user.name "abusiraj84"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add -A
          git commit -m "Deploy plugin with only dist, classes, and plugin.php" || echo "No changes to commit"
          git remote set-url origin https://abusiraj84:${{ secrets.GITHUB_TOKEN }}@github.com/abusiraj84/wp-react.git
          git push origin HEAD:staging --force

  # Job 5: Create Pull Request to Master
  create-pull-request:
    runs-on: ubuntu-latest
    needs: push-to-staging
    steps:
      - name: Create Pull Request to Master
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: master
          source_branch: staging
          pr_title: "Deploy from Staging to Master"
          pr_body: "This is an automated PR to merge staging into master after build and deploy."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
