name: Sync main to staging and create PR to master

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.17.0"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the build script
      - name: Run build
        run: npm run build

  push_main:
    name: Push to Main
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure Git (Set identity for the runner)
      - name: Configure Git
        run: |
          git config --global user.email "abusiraj84@gmail.com"
          git config --global user.name "abusiraj84"

      # Step 3: Push changes to main
      - name: Push to main branch
        run: |
          git checkout main
          git pull origin main
          git push origin main --force

  push_staging:
    name: Push to Staging
    runs-on: ubuntu-latest
    needs: push_main

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure Git (Set identity for the runner)
      - name: Configure Git
        run: |
          git config --global user.email "abusiraj84@gmail.com"
          git config --global user.name "abusiraj84"

      # Step 3: Push main branch to staging
      - name: Push main to staging
        run: |
          git fetch origin
          git checkout main
          git pull origin main
          git push origin main:staging --force

  pr_master:
    name: PR to Master
    runs-on: ubuntu-latest
    needs: push_staging

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure Git (Set identity for the runner)
      - name: Configure Git
        run: |
          git config --global user.email "abusiraj84@gmail.com"
          git config --global user.name "abusiraj84"

      # Step 3: Ensure master branch exists
      - name: Ensure master branch exists
        run: |
          if ! git ls-remote --exit-code --heads origin master; then
            git checkout --orphan master
            git rm -rf .
            echo "# Master branch" > README.md
            git add README.md
            git commit -m "Initial commit for master branch"
            git push origin master
          else
            echo "Master branch already exists"
          fi

      # Step 4: Rebase staging onto master
      - name: Rebase staging onto master
        run: |
          git fetch origin
          git checkout master
          git pull origin master
          git checkout staging
          git rebase --onto master staging
          git checkout master
          git merge staging
          git push origin master --force

      # Step 5: Cherry-pick the latest commit from staging automatically
      - name: Cherry-pick the latest commit from staging
        run: |
          git fetch origin
          git checkout master
          # Get the latest commit hash from staging
          LATEST_COMMIT=$(git log origin/staging --pretty=format:'%H' -n 1)
          echo "Cherry-picking commit: $LATEST_COMMIT"
          # Cherry-pick the latest commit
          git cherry-pick $LATEST_COMMIT
          # Push the changes to master
          git push origin master

      # Step 6: Create a pull request from staging to master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master # Target branch (master)
          branch: staging # Source branch (staging)
          title: "Pull request from staging to master"
          body: "This is an automated pull request created after syncing main to staging."
