name: Sync main to staging

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (if needed for your build)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.17.0"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the build script
      - name: Run build
        run: npm run build

      # Step 5: Configure Git (Set identity for the runner)
      - name: Configure Git
        run: |
          git config --global user.email "abusiraj84@gmail.com"
          git config --global user.name "abusiraj84"

      # Step 6: Push main to staging
      - name: Push main to staging
        run: |
          git fetch origin
          git checkout main
          git pull origin main
          git push origin main:staging --force

      # Step 7: Trigger the second workflow using curl
      - name: Trigger pull request workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/create-pull-request.yml/dispatches \
            -d '{"ref":"main"}'
